import jsPDF from 'jspdf';
import { Competitor } from '../types/competitor';

const COLUMNS = [
  { header: 'Name', width: 40 },
  { header: 'Description', width: 70 },
  { header: 'Pricing', width: 40 },
  { header: 'Support', width: 40 }
];

export const generateCompetitorPDF = (competitors: Competitor[], searchQuery: string) => {
  const pdf = new jsPDF();
  
  // Add title
  pdf.setFontSize(20);
  pdf.setTextColor(0, 0, 0);
  pdf.text('Competitor Analysis Comparison Chart', 20, 20);
  
  // Add search query
  pdf.setFontSize(12);
  pdf.text(`Analysis for: ${searchQuery}`, 20, 30);
  
  // Add headers
  let yPos = 45;
  let xPos = 20;
  
  pdf.setFillColor(0, 0, 0);
  pdf.setTextColor(255, 255, 255);
  
  COLUMNS.forEach(column => {
    pdf.rect(xPos, yPos - 5, column.width, 10, 'F');
    pdf.text(column.header, xPos + 2, yPos);
    xPos += column.width;
  });
  
  // Reset text color for content
  pdf.setTextColor(0, 0, 0);
  yPos += 10;
  
  // Add competitor data
  competitors.forEach((competitor, index) => {
    if (yPos > 250) {
      pdf.addPage();
      yPos = 20;
    }
    
    xPos = 20;
    const rowHeight = 20;
    
    // Alternate row background
    if (index % 2 === 0) {
      pdf.setFillColor(245, 245, 245);
      pdf.rect(xPos, yPos - 5, COLUMNS.reduce((acc, col) => acc + col.width, 0), rowHeight, 'F');
    }
    
    // Name
    pdf.text(competitor.name, xPos + 2, yPos);
    xPos += COLUMNS[0].width;
    
    // Description (with word wrap)
    const descLines = pdf.splitTextToSize(competitor.description, COLUMNS[1].width - 4);
    pdf.text(descLines, xPos + 2, yPos);
    xPos += COLUMNS[1].width;
    
    // Pricing
    const pricingText = typeof competitor.pricing === 'string' 
      ? competitor.pricing 
      : `${competitor.pricing?.plan}: ${competitor.pricing?.price}`;
    pdf.text(pricingText || 'N/A', xPos + 2, yPos);
    xPos += COLUMNS[2].width;
    
    // Support (combining available channels)
    const supportChannels = [];
    if (competitor.linkedin) supportChannels.push('LinkedIn');
    if (competitor.twitter) supportChannels.push('Twitter');
    if (competitor.url) supportChannels.push('Website');
    pdf.text(supportChannels.join(', ') || 'N/A', xPos + 2, yPos);
    
    yPos += rowHeight;
  });
  
  // Add source
  pdf.setFontSize(10);
  pdf.text('Generated by Know Your Competitor', 20, pdf.internal.pageSize.height - 10);
  
  return pdf;
};